// <auto-generated />
using Data_App;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data_App.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.13");

            modelBuilder.Entity("Data_App.Entities.EmployeeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DateOfEmployment")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("time in the company");

                    b.Property<int>("Departament")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PESEL")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("TEXT");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfEmployment = "11.10.2008",
                            Departament = 3,
                            FirstName = "Jan",
                            LastName = "Nowak",
                            PESEL = "8902137123",
                            Position = "Manager"
                        },
                        new
                        {
                            Id = 2,
                            DateOfEmployment = "13.05.2004",
                            Departament = 3,
                            FirstName = "Jan",
                            LastName = "Kowalski",
                            PESEL = "6902137420",
                            Position = "Manager",
                            ReleaseDate = "11.10.2008"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
